package apap.poc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Persona implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("edad")
   private java.lang.Integer edad;
   @org.kie.api.definition.type.Label("nombre")
   private java.lang.String nombre;
   @org.kie.api.definition.type.Label("salario")
   private java.lang.Integer salario;
   @org.kie.api.definition.type.Label("sexo")
   private java.lang.String sexo;
   @org.kie.api.definition.type.Label("estadoCivil")
   private java.lang.String estadoCivil;
   @org.kie.api.definition.type.Label("montoCredito")
   private java.lang.Integer montoCredito;
   @org.kie.api.definition.type.Label("cedula")
   private java.lang.String cedula;
   @org.kie.api.definition.type.Label("aptoCredito")
   private boolean aptoCredito;

   @org.kie.api.definition.type.Label("segmento")
   private java.lang.String segmento;

   @org.kie.api.definition.type.Label("esCliente")
   private java.lang.Boolean esCliente;

   @org.kie.api.definition.type.Label("aprobadoAnalista")
   private java.lang.Boolean aprobadoAnalista;

   @org.kie.api.definition.type.Label("correoElectronico")
   private java.lang.String correoElectronico;

   @org.kie.api.definition.type.Label("direccion")
   private java.lang.String direccion;

   @org.kie.api.definition.type.Label("telefono")
   private java.lang.Integer telefono;

   @org.kie.api.definition.type.Label(value = "cuotas")
   private java.lang.Integer cuotas;

   public Persona()
   {
   }

   public java.lang.Integer getEdad()
   {
      return this.edad;
   }

   public void setEdad(java.lang.Integer edad)
   {
      this.edad = edad;
   }

   public java.lang.String getNombre()
   {
      return this.nombre;
   }

   public void setNombre(java.lang.String nombre)
   {
      this.nombre = nombre;
   }

   public java.lang.Integer getSalario()
   {
      return this.salario;
   }

   public void setSalario(java.lang.Integer salario)
   {
      this.salario = salario;
   }

   public java.lang.String getSexo()
   {
      return this.sexo;
   }

   public void setSexo(java.lang.String sexo)
   {
      this.sexo = sexo;
   }

   public java.lang.String getEstadoCivil()
   {
      return this.estadoCivil;
   }

   public void setEstadoCivil(java.lang.String estadoCivil)
   {
      this.estadoCivil = estadoCivil;
   }

   public java.lang.Integer getMontoCredito()
   {
      return this.montoCredito;
   }

   public void setMontoCredito(java.lang.Integer montoCredito)
   {
      this.montoCredito = montoCredito;
   }

   public java.lang.String getCedula()
   {
      return this.cedula;
   }

   public void setCedula(java.lang.String cedula)
   {
      this.cedula = cedula;
   }

   public boolean isAptoCredito()
   {
      return this.aptoCredito;
   }

   public void setAptoCredito(boolean aptoCredito)
   {
      this.aptoCredito = aptoCredito;
   }

   public java.lang.String getSegmento()
   {
      return this.segmento;
   }

   public void setSegmento(java.lang.String segmento)
   {
      this.segmento = segmento;
   }

   public java.lang.Boolean getEsCliente()
   {
      return this.esCliente;
   }

   public void setEsCliente(java.lang.Boolean esCliente)
   {
      this.esCliente = esCliente;
   }

   public java.lang.Boolean getAprobadoAnalista()
   {
      return this.aprobadoAnalista;
   }

   public void setAprobadoAnalista(java.lang.Boolean aprobadoAnalista)
   {
      this.aprobadoAnalista = aprobadoAnalista;
   }

   public java.lang.String getCorreoElectronico()
   {
      return this.correoElectronico;
   }

   public void setCorreoElectronico(java.lang.String correoElectronico)
   {
      this.correoElectronico = correoElectronico;
   }

   public java.lang.String getDireccion()
   {
      return this.direccion;
   }

   public void setDireccion(java.lang.String direccion)
   {
      this.direccion = direccion;
   }

   public java.lang.Integer getTelefono()
   {
      return this.telefono;
   }

   public void setTelefono(java.lang.Integer telefono)
   {
      this.telefono = telefono;
   }

   public java.lang.Integer getCuotas()
   {
      return this.cuotas;
   }

   public void setCuotas(java.lang.Integer cuotas)
   {
      this.cuotas = cuotas;
   }

   public Persona(java.lang.Integer edad, java.lang.String nombre,
         java.lang.Integer salario, java.lang.String sexo,
         java.lang.String estadoCivil, java.lang.Integer montoCredito,
         java.lang.String cedula, boolean aptoCredito,
         java.lang.String segmento, java.lang.Boolean esCliente,
         java.lang.Boolean aprobadoAnalista, java.lang.String correoElectronico,
         java.lang.String direccion, java.lang.Integer telefono,
         java.lang.Integer cuotas)
   {
      this.edad = edad;
      this.nombre = nombre;
      this.salario = salario;
      this.sexo = sexo;
      this.estadoCivil = estadoCivil;
      this.montoCredito = montoCredito;
      this.cedula = cedula;
      this.aptoCredito = aptoCredito;
      this.segmento = segmento;
      this.esCliente = esCliente;
      this.aprobadoAnalista = aprobadoAnalista;
      this.correoElectronico = correoElectronico;
      this.direccion = direccion;
      this.telefono = telefono;
      this.cuotas = cuotas;
   }

}