package apap.poc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Resultado implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "URL")
   private java.lang.String URL;

   public Resultado()
   {
   }

   public java.lang.String getURL()
   {
      return this.URL;
   }

   public void setURL(java.lang.String URL)
   {
      this.URL = URL;
   }

   public Resultado(java.lang.String URL)
   {
      this.URL = URL;
   }

}